sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - EMAIL_ADDRESS
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=./PACKAGE_NAME.rosinstall
    - ROS_DISTRO=kinetic  ROS_REPO=ros              TEST=clang-format
script:
  - source .travis/travis.sh
addons:
  # https://docs.travis-ci.com/user/ssh-known-hosts/
  ssh_known_hosts:
    - bitbucket.org